---
development:
  cloud_name: americano
  api_key: '981327884294715'
  api_secret: mEAFPR1iDhpavnP4EesJcgZ4aw8
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: americano
  api_key: '981327884294715'
  api_secret: mEAFPR1iDhpavnP4EesJcgZ4aw8
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: americano
  api_key: '981327884294715'
  api_secret: mEAFPR1iDhpavnP4EesJcgZ4aw8
  enhance_image_tag: true
  static_image_support: false
